### ISSUE TITLE
Textbox validation

### ISSUE THREAD

**Issue by Gustavo079** [xXChAvE2Xx/kren#5]
That the administrator can view the created courses, without leaving empty fields.
A special test case was created for this bug, where the form in which said error was found and the tests that were carried out are written.

- click on some course and edit values
  - [x] Check that the values are not empty.

**Comment by xXChAvE2Xx** [comment]
I found another bug, if you have scheduled a course, the button to generate certificates is **missing**. @YxMARCKxY 
![Screenshot 2021-11-02 172234](https://user-images.githubusercontent.com/54995852/139965260-2b805e5e-98f0-4856-81a9-b13821ccbd11.png)

**Comment by YxMARCKxY** [comment]
> I found another bug, if you have scheduled a course, the button to generate certificates is **missing**. @YxMARCKxY 
> ![Screenshot 2021-11-02 172234](https://user-images.githubusercontent.com/54995852/139965260-2b805e5e-98f0-4856-81a9-b13821ccbd11.png)
> 

not is a bug @xXChAvE2Xx is obvious that if a course is being showing, you should not be able to generate certificates until to the current course be finish. (i program this with these finallity) but if you want that i change this, in your next coment apeak me about it

**Comment by xXChAvE2Xx** [comment]
> > I found another bug, if you have scheduled a course, the button to generate certificates is **missing**. @YxMARCKxY 
> > ![Screenshot 2021-11-02 172234](https://user-images.githubusercontent.com/54995852/139965260-2b805e5e-98f0-4856-81a9-b13821ccbd11.png)
> > 
> 
> not is a bug @xXChAvE2Xx is obvious that if a course is being showing, you should not be able to generate certificates until to the current course be finish. (i program this with these finallity) but if you want that i change this, in your next coment apeak me about it

Okay, I had seen it as a bug but now it makes sense. @YxMARCKxY

**Comment by YxMARCKxY** [comment]
> That the administrator can view the created courses, without leaving empty fields.
> A special test case was created for this bug, where the form in which said error was found and the tests that were carried out are written.
> 
> - click on some course and edit values
>   - [ ] Check that the values are not empty.

jsjs how is it that  the admin not should will can view the courses created without leaving fields empty? you mean to the inputs of the form no? and how this affect tye view of the courses

**Comment by xXChAvE2Xx** [comment]
Bug - When deleting a course, the description section is not updated and the description of the deleted course is still displayed. @YxMARCKxY 
![bug](https://user-images.githubusercontent.com/54995852/140566480-32727b06-671f-45db-a7b1-ad7a8ed608bf.png)
